### ISSUE TITLE
Please give me the example code TCP Sync

### ISSUE THREAD

**Issue by Multiple-Personality** [subes/invesdwin-webproxy#2]
I found you at
https://stackoverflow.com/questions/11547082/fastest-way-to-scan-ports-with-java/44465268#44465268

I want faster port scanning with TCP Syn instead of
`public boolean portIsOpen(String ip, int port, int timeout) {
    try {
        Socket socket = new Socket();
        socket.connect(new InetSocketAddress(ip, port), timeout);
        socket.close();
        return true;
    } catch (Exception ex) {
        return false;
    }
}`
I heard you say your library can do that.Please give me the example code so I made it thank you very much

**Comment by subes** [comment]
Just look at the code and unit tests there. Please only open tickets for issues with the code.
